spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 9090

zuul:
  ignoredServices: configservice,mq-api   #不对外提供服务
  SendErrorFilter:
    post:
      disable: true
  max:
    host:
      connections: 5000
      socket-timeout-millis: 15000
      connect-timeout-millis: 15000
  routes:
    webAdmin:
      serviceId: webAdmin
      path: /webAdmin/**
      stripPrefix: true